---
- name: deploy Kadalu Kubectl plugin
  get_url:
    mode: '0555'
    owner: 'root'
    group: 'root'
    url: 'https://github.com/kadalu/kadalu/releases/latest/download/kubectl-kadalu'
    dest: '/usr/local/bin/'

- name: Ensure pip3 exists
  package:
    name: 'python3-pip'
    state: 'present'

# Due to bug in kubernetes 12.00+ we need to use an older version
# Installing just openshift will bump the kubernetes version
- name: Install mandatory pip3 modules
  pip:
    state: 'present'
    name: 
    - 'openshift==0.11.0'
    - 'kubernetes==11.0.0'

- name: Verify/install kadalu
  block:
  - name: Obtain the yaml defintions
    get_url:
      url: "{{ item.url }}"
      dest:  "{{ item.dest }}"
    loop:
    - { url: 'https://raw.githubusercontent.com/kadalu/kadalu/{{ kadalu_branch }}/manifests/kadalu-operator.yaml', 
        dest: '/tmp/kadalu-operator.yaml' }
    - { url: 'https://raw.githubusercontent.com/kadalu/kadalu/{{ kadalu_branch }}/manifests/csi-nodeplugin.yaml', 
        dest: '/tmp/csi-nodeplugin.yaml' }
    
  - name: Apply the 2 yaml files
    k8s:
      state: present
      src: "{{ item }}"
    loop:
    - '/tmp/kadalu-operator.yaml'
    - '/tmp/csi-nodeplugin.yaml'
    run_once: True
