---
- name: Setting up Quota prerequisites for external gluster vols
  become: True
  become_method: 'sudo'
  hosts: kubernetes_nodes
  gather_facts: True
  vars:
    remote_gluster_volume: 'kubernetes'
 
  roles:
    - remote_gluster_quota
